In [1]:
from mxnet import nd

In [3]:
#=========================第一部分：基础使用=============================
#用arange函数创建一个行向量
x=nd.arange(12);
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [4]:
#用shape属性来获取NDArray实例的形状
x.shape

(12,)

In [5]:
#用size获取NDArray的长度
x.size

12

In [6]:
#reshape改变行向量的形状
x.reshape(3,4)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [7]:
#创建各元素为0，形状为（2，3，4）的张量
#实际上之前创建的向量和矩阵都是特殊的张量
nd.zeros((2,3,4))



[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [8]:
#类似的我们呢可以创建各元素为1的张量
nd.ones((3,4))



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [9]:
#我们也可以通过python的列表指定需要创建的NDArray中每个元素的值
Y=nd.array([[2,3,4,5],[6,7,8,9],[1,2,3,4]])
Y


[[2. 3. 4. 5.]
 [6. 7. 8. 9.]
 [1. 2. 3. 4.]]
<NDArray 3x4 @cpu(0)>

In [10]:
#创建一个形状为（3，4）的NDArray，它的每个元素都采样于均值为0，标准差为1的正态分布
nd.random.normal(0,1,shape=(3,4))


[[ 1.1630787   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546344  -0.54877394]]
<NDArray 3x4 @cpu(0)>