In [9]:
from mxnet import nd;

In [10]:
#接下来进行一些运算操作
x=nd.arange(12);
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [11]:
#先搞一个大写的三行四列的X
X=x.reshape((3,4));
X
# X=x.reshape((-1,7));
# X
# 如果能满足这么多列，就全部显示，不满足就少显示一行
# 结果:
# [[0. 1. 2. 3. 4. 5. 6.]]
# <NDArray 1x7 @cpu(0)>




#X[:,2] #[ 2.  6. 10.] #得到了第二列的值


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [12]:
#再搞一个Y
Y=nd.array([[2,1,4,3],[2,1,4,3],[2,1,4,3]]);
Y


[[2. 1. 4. 3.]
 [2. 1. 4. 3.]
 [2. 1. 4. 3.]]
<NDArray 3x4 @cpu(0)>

In [13]:
#然后我们看下元素乘法
X*Y


[[ 0.  1.  8.  9.]
 [ 8.  5. 24. 21.]
 [16.  9. 40. 33.]]
<NDArray 3x4 @cpu(0)>

In [14]:
#然后我们看下元素除法
X/Y


[[0.        1.        0.5       1.       ]
 [2.        5.        1.5       2.3333333]
 [4.        9.        2.5       3.6666667]]
<NDArray 3x4 @cpu(0)>

In [15]:
#按元素做指数运算
Y.exp()


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 7.389056   2.7182817 54.59815   20.085537 ]]
<NDArray 3x4 @cpu(0)>

In [16]:
#做矩阵乘法
#由于X是3行4列的矩阵，Y转置为4行3列的，
#两矩阵想乘可以得到三行三列的矩阵
nd.dot(X,Y.T)


[[18. 18. 18.]
 [58. 58. 58.]
 [98. 98. 98.]]
<NDArray 3x3 @cpu(0)>

In [17]:
#两个矩阵的链接，有纬度0和纬度1的区分
#首先是纬度0
nd.concat(X,Y,dim=0)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 2.  1.  4.  3.]
 [ 2.  1.  4.  3.]]
<NDArray 6x4 @cpu(0)>

In [18]:
#然后是纬度1
nd.concat(X,Y,dim=1)


[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  2.  1.  4.  3.]
 [ 8.  9. 10. 11.  2.  1.  4.  3.]]
<NDArray 3x8 @cpu(0)>

In [19]:
#条件判断式可以产生新的元素为1的NDArray，如果相同位置的值为相等，则返回1，反之返回0
X==Y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [20]:
#对所有元素求和，得到只有一个元素的NDArray
X.sum()



[66.]
<NDArray 1 @cpu(0)>

In [21]:
#L2范数，范数的意义是为了反应距离，normal,得到只有一个元素的NDArray
X.norm()


[22.494442]
<NDArray 1 @cpu(0)>

In [27]:
#我们可以使用asscalar将结果换为python中的标量
#从一个数组样式转换成标量
X.norm().asscalar()


22.494442

In [28]:
Z = x.reshape(3,4);
#(1)concat将两个数组链接在一起，dim默认为0是横着排列的
#(2)power是将Z每一位取2次方得到的数组
W = nd.concat(Z,nd.power(Z,2))
W


[[  0.   1.   2.   3.   0.   1.   4.   9.]
 [  4.   5.   6.   7.  16.  25.  36.  49.]
 [  8.   9.  10.  11.  64.  81. 100. 121.]]
<NDArray 3x8 @cpu(0)>

In [30]:
#在正太分布区间中生成值
labels = nd.random.normal(scale=0.1,shape=(3,4))
labels


[[ 0.11630785  0.04838046  0.02995635  0.01530255]
 [-0.11688148  0.15580711 -0.05459446 -0.23556297]
 [ 0.05414402  0.26785064  0.12546344 -0.05487741]]
<NDArray 3x4 @cpu(0)>