In [3]:
from mxnet import nd;

In [4]:
#当两个形状不同的NDArray按元素运算时，可能会触发广播机制：
#广播机制：先适当复制元素，使这两个NDArray相同后再按元素运算

In [5]:
A = nd.arange(3).reshape((3,1))#一个三行一列
A


[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>

In [6]:
B = nd.arange(2).reshape((1,2))#一个一行两列
B


[[0. 1.]]
<NDArray 1x2 @cpu(0)>

In [7]:
#由于A、B分别是三行一列、和一行两列的矩阵，如果要计算A+B
#第一列的三个元素被广播复制到第二列
#B第一行的元素也被复制到第二行，第三行
#这样A和B型形状相同，就可以完成元素相加

A+B



[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>