In [27]:
from mxnet import nd;
x=nd.arange(12);
x
X = x.reshape((3,4));
X
Y = nd.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
Y


[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
<NDArray 3x4 @cpu(0)>

In [28]:
#在前边的例子，我们对每个操作新开内存来存储运算结果
#我们可以使用python自带的id函数，如果两个对象的id相同，则返回true
before = id(Y);
Y=X+Y;
id(Y)==before

False

In [29]:
#如果想指定结果到特定内存，我们可以使用前边的索引进行替换操作
#zeros_like可以创建一个和其他NDArray形状相同，但是元素为0的NDArray
Z = Y.zeros_like();
bef = id(Z);
#用X+Y得到的值通过索引替换原来的Z元素值
Z[:]=X+Y;
id(Z)==bef

True

In [30]:
#实际上，上例中我们还是新开了临时内存来存储X+Y
#如果想避免这种内存开销，我们可以使用全名函数中的out参数
N = Y.zeros_like();
be = id(N);
nd.elemwise_add(X,Y,out=N)
id(N)==be


True

In [32]:
#如果X的值在之后的程序中不会复用，那么我们也可以使用X[:]=X+Y;或者X+=Y,来减少内存消耗
b = id(X);
X+=Y;
id(X)==b

True