In [4]:
import numpy as np;
from mxnet import nd;

In [5]:
#将NumPy实例转换成NDArray实例
P = np.ones((2,3))
P
#通过nd.array转换
D = nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [6]:
#将NDArray实例转化成NumPy实例
D.asnumpy()
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [ ]:
#小结
#（1）NDArray是框架里边存储和变换数据的主要工具
#（2）可以轻松的对NDArray创建、运算、指定索引，并和NumPy之间相互变换
