In [6]:
from mxnet import autograd;
from mxnet import nd;

In [7]:
x=nd.arange(4).reshape((4,1))
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [8]:
#调用attach_grad函数来申请存储梯度所需要的内存
x.attach_grad()
x.grad #函数还没有建立，没有梯度


[[0.]
 [0.]
 [0.]
 [0.]]
<NDArray 4x1 @cpu(0)>

In [9]:
#定义有关变量x的函数，调用record函数来记录有关梯度计算的记录
#默认为了节省内存是不记录的
print(autograd.is_training());#预测模式
with autograd.record():
    print(autograd.is_training());#调用record转化为了训练模式了
    y = 2 * nd.dot(x.T,x)#开始变换线性函数
y.backward();#在有了运动的基础上，开始求梯度
#由于x的形状是4行1列，y是一个标量
#如果y不是一个标量，mxnet默认将对y中元素求和得到新的变量，再求该变量对x的梯度



False
True


In [24]:
assert (x.grad - 4 * x).norm().asscalar() == 0
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>